name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set write permissions for build
        run: |
          mkdir .jekyll-cache build
          chmod 777 ./Gemfile.lock ./.jekyll-cache ./build

      - name: Docker, jekyll build
        run: docker run --rm --volume="$PWD:/srv/jekyll" jekyll/builder:latest jekyll b -d build

      - name: Deploy to site branch
        run: |
          git config --global user.email "GHactions@howzitcal.xyz"
          git config --global user.name "CDF GA DEPLOY"

          git clone -b site https://.:${{ secrets.PAT }}@github.com/${{github.repository}} target

          if [ -f ./target/CNAME ];
          then
            cp ./target/CNAME ./build/
          fi
          rm -vrf ./target/*
          cp -vrf ./build/* ./target

          (
            curr_date=$(date +'%m/%d/%Y')
            cd ./target

            git add .
            git commit -m "Automatic publish ${curr_date}"
            git push -fq origin site
          )
